import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
});

// Ensure dist directory exists and copy required files
mkdirSync('dist', { recursive: true });

const filesToCopy = ['manifest.json', 'styles.css'];
for (const file of filesToCopy) {
    try {
        copyFileSync(file, `dist/${file}`);
        console.log(`\u2713 Copied ${file} to dist/`);
    } catch (err) {
        console.warn(`\u26a0 Warning: Could not copy ${file}: ${err.message}`);
    }
}

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
